### ISSUE TITLE
 AWS credentials invalid / Invalid StreamArn

### ISSUE THREAD

**Issue by vaneavasco** [awslabs/logstash-input-dynamodb#18]
I'm getting an error with my local dynamodb instance and also with my amazon account:

```
Error: AWS credentials invalid or not found in the provider chain
Invalid StreamArn (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: ValidationException;
```

I'm running this image: https://hub.docker.com/r/mantika/logstash-dynamodb-streams/

```
docker run mantika/logstash-dynamodb-streams --verbose -e '
input { 
    dynamodb{
    endpoint => "dynamodb.eu-west-1.amazonaws.com" 
    streams_endpoint => "streams.dynamodb.eu-west-1.amazonaws.com" 
    view_type => "new_and_old_images" 
    aws_access_key_id => "blablabla" 
    aws_secret_access_key => "blablabla" 
    table_name => "mytable"
   } 
} 
filter {
    dynamodb {}
}
output { 
    elasticsearch 
        { hosts => "localhost" } 
stdout { } 
}'
```

Any ideas?

**Comment by marcosnils** [comment]
@stefanvasco I'm sure this must be some silly error on your side as this works fine in prod in my case. Are you sure that your dynamodb tables are in the corresponding regions and that the credentials you're using have the correct policy to call dynamodb actions?

**Comment by vaneavasco** [comment]
Yup, you're right, my bad, actually I messed up the stream types. Thank you! Oh and it works like a charm on my local dynamodb with your region suggestion!

**Comment by marcosnils** [comment]
perfect.

Can you please close this issue?
