### ISSUE TITLE
Restarting Logstash

### ISSUE THREAD

**Issue by ahmedammar** [awslabs/logstash-input-dynamodb#7]
Am I missing something or is it not possible for the dynamodb input plugin to only send newer items to elasticsearch? Right now all I can find is that it will duplicate items on each restart ...

**Comment by marcosnils** [comment]
@ahmedammar you need to set the perform_scan variable to false in the input plugin to prevent logstash scanning the entire table upon restarting.  Read the README here: https://github.com/awslabs/logstash-input-dynamodb

**Comment by ahmedammar** [comment]
Thanks for the quick response, trust me I've read that README plenty of times :)

I guess I misunderstood the meaning and set it to 'true'. Just tried with 'false', seems to be working. Awesome thanks!

**Comment by marcosnils** [comment]
Sure, :+1:
